function shade_regions(ax,params,options)
%SHADE_REGIONS colors in the R and S regions on figures
%
%last updated 08/25/26 by Adam Petrucci
arguments (Input)
    ax      % the axis to shade in
    params  % parameters defining R and S
end
arguments (Input)
    options.Region_Labels logical = false   % add regions to legend?
end

    yl = ylim(ax);

    % Responsive region R
    patch_r = patch(ax, ...
                    [params.r1 params.r2 params.r2 params.r1], ...
                    [yl(1) yl(1) yl(2) yl(2)], ...
                    [0.85 0.85 0.85], ...
                    'FaceAlpha',0.25, ...
                    'EdgeColor','none', ...
                    'DisplayName','R');

    % Signaling region S
    patch_s = patch(ax, ...
                    [params.s1 params.s2 params.s2 params.s1], ...
                    [yl(1) yl(1) yl(2) yl(2)], ...
                    [0.70 0.80 0.95], ...
                    'FaceAlpha',0.25, ...
                    'EdgeColor','none', ...
                    'DisplayName','S');

    if ~options.Region_Labels
        set(get(get(patch_s, 'Annotation'), 'LegendInformation'),'IconDisplayStyle', 'off');
        set(get(get(patch_r, 'Annotation'), 'LegendInformation'),'IconDisplayStyle', 'off');
    end

end