function return_data = format_tiling(tl,c_labels,r_labels,options)
%FORMAT_TILING Given a tiling of simulation data, apply a standard format
%
%last updated 10/08/25
arguments (Input)
    tl                  % the tiledlayout to format
    c_labels            % column labels
    r_labels            % row labels
end
arguments (Input)
    options.link = false        % link axes by standardization
end

    % Collection Inputs
    link = options.link;

    cl = length(c_labels);
    rl = length(r_labels);

    % Remove labels from subplots
    axs = findall(tl, 'Type', 'axes');
    for k = 1:length(axs)
        axs(k).XTickLabel = {};
        axs(k).YTickLabel = {};
        xlabel(axs(k), '');
        ylabel(axs(k), '');
    end

    % Add labels to parent figure
    title(tl,"Experiment",'FontWeight', 'bold');
    xlabel(tl,'Position');
    ylabel(tl,'Density');

    % Check about standardizing axes
    if link
        linkaxes(axes,'y');
    end

    % ====== Column Labels (Bottom) ======
    labelWidth = 0.05;
    labelHeight = 0.05;

    for j = 1:cl
        pos = axs(cl-j+1).Position;
        xpos = pos(1) + pos(3)/2 - labelWidth/2;
        ypos = 0.25*pos(2);
        annotation('textbox', ...
            [xpos, ypos, labelWidth, labelHeight], ...
            'String', c_labels(j), ...
            'EdgeColor', 'none', ...
            'HorizontalAlignment', 'center', ...
            'FontWeight', 'bold', ...
            'FontSize', 11);
    end

    % ====== Row Labels (Left) ======

    for i = 1:rl
        pos = axs(i*cl).Position;
        xpos = 0.8*pos(1);
        ypos = pos(2) + pos(4)/2 - 0.9*labelHeight;
        annotation('textbox', ...
            [xpos, ypos, labelWidth, labelHeight], ...
            'String', r_labels(i), ...
            'EdgeColor', 'none', ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'Rotation', 90, ...
            'FontWeight', 'bold', ...
            'FontSize', 11);
    end

    annotation('textbox', ...
        [0.9*axs(cl).Position(1),0.25*axs(cl).Position(2), labelWidth, labelHeight], ...
        'String', 'Time', ...
        'EdgeColor', 'none', ...
        'HorizontalAlignment', 'center', ...
        'FontWeight', 'bold', ...
        'FontSize', 11);
    annotation('textbox', ...
        [0.8*axs(cl).Position(1),0.1*axs(cl).Position(2), labelWidth, labelHeight], ...
        'String', 'Particles', ...
        'EdgeColor', 'none', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'Rotation', 90, ...
        'FontWeight', 'bold', ...
        'FontSize', 11);

    return_data = tl;

end