function return_data = ct_exp(d)
    f = @(t) exp(-1/(d/2)^2-t.^2);
    n_f = integral(f,-(d/2),(d/2));
    return_data = @(start,stop) @(x) ...
        0*(x < start-d/2) + ...
        (start-d/2 < x).*(x < start+d/2).*arrayfun(@(y) integral(@(z) f(z-start), start-d/2, y) / n_f, x) + ...
        1*(start+d/2 < x).*(x< stop-d/2) + ...
        (stop-d/2 < x).*(x < stop+d/2).*arrayfun(@(y) 1-integral(@(z) f(stop-z), stop-d/2, y) / n_f, x) + ...
        0*(stop+d/2 < x);
end