function return_data = ct_tanh_a(d)
    return_data = @(start,stop) @(x) ...
        0*(x < start-d/2) + ...
        (start-d/2 < x).*(x < start+d/2).*(0.5*(1+tanh(d*(x-start)./(d^2-(x-start).^2)))) + ...
        1*(start+d/2 < x).*(x< stop-d/2) + ...
        (stop-d/2 < x).*(x < stop+d/2).*(0.5*(1+tanh(d*(stop-x)./(d^2-(stop-x).^2)))) + ...
        0*(stop+d/2 < x);
end